Merge new pipeline updates
YeoLab/eclip-qc pull request #13
Opened 2023-07-20 05:16 UTC by howardxu520

2023-07-20 19:12 UTC, byee4 commented on config.yaml
> +  - "/home/bay001/projects/adri_chimeric_clips_20220811/temporary_data/crispr_clip_cas711_se_GRCh38_v2_small/results/Cas711_SE_GRCh38.EEF1A1_22nt_Cas711_IP_r1.umi.r1.fq.genome-mapped.bam"
If possible, let's keep the example config as-is, and point to small data/files that we've already created

2023-07-20 19:13 UTC, byee4 commented on scripts/blastresults_piechart_old.py
Don't need to make copies of "old" since they'll be stored in your testing branch

2023-07-20 19:14 UTC, byee4 commented on examples.txt
Remove

2023-07-20 19:14 UTC, byee4 commented on jupyter_testing/IP_n_interest.csv
Remove

2023-07-20 19:14 UTC, byee4 commented on jupyter_testing/another.ipynb
This should stay in your testing branch

2023-07-20 19:16 UTC, byee4 commented on jupyter_testing/error_log.txt
maybe have a "Jupyter testing" branch where all of your Jupyter notebook stuff can live, and keep your dev_improve branch to only improvement/additions to the actual scripts

2023-07-20 19:18 UTC, byee4 requested changes
Hi Shuhao, I reviewed your PR and I think your changes are good, but would like to clean up/migrate your Jupyter notebook stuff over to somewhere else. See if you can limit the merge to only improvements to the scripts that will be used by your Snakefile

2023-07-21 03:33 UTC, howardxu520 commented
OK, Let me keep all my debugging materials into a folder and put that folder under gitignore.

2023-07-21 03:59 UTC, closed without merging